# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-03 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160703_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='brand_id',
        ),
    ]
