# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-13 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160703_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
