# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-13 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20160713_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'ACTIVE'), (1, 'OVERDUE'), (2, 'COMPLETED'), (3, 'LOSS')], default=0, max_length=1),
        ),
    ]
