# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-13 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20160713_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('a', 'ON LOAN'), ('o', 'OVERDUE'), ('c', 'COMPLETED'), ('x', 'LOSS')], default=0, max_length=1),
        ),
    ]
