# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-13 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20160713_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('a', 'ON LOAN'), ('o', 'OVERDUE'), ('c', 'COMPLETED'), ('x', 'LOSS')], default='a', max_length=1),
        ),
    ]
